hpc <- read.table("household_power_consumption.txt", header=TRUE, sep = ";", dec = ".")
hpcdates <- subset(hpc, Date == "1/2/2007" | Date == "2/2/2007")
png(file = "plot1.png", bg = "white", width = 480, height = 480)
hist(as.numeric(hpcdates$Global_active_power), main ="Global Active Power", xlab = "Global Active Power (kilowatts)", ylab="Frequency", col = "#D93822")
dev.off()
